@startuml ExpressaoEstranha
start

:Mostrar "Digite o valor de A:";
:Leia a;
:Mostrar "Digite o valor de B:";
:Leia b;
:Mostrar "Digite o valor de C:";
:Leia c;

:resultado = ((m.potencia(a, 2.0) + m.potencia(b, 3.0) + m.potencia(c, 4.0)) / 9.0) + 1;

if (resultado >= 0 e resultado <= 10?) then (Sim)
  :Mostrar "Expressão é 10%";
elseif (resultado >= 11 e resultado <= 20?) then (Sim)
  :Mostrar "Expressão é 20%";
elseif (resultado >= 21 e resultado <= 50?) then (Sim)
  :Mostrar "Expressão é 50%";
elseif (resultado >= 51 e resultado <= 75?) then (Sim)
  :Mostrar "Expressão é 75%";
elseif (resultado > 75?) then (Sim)
  :Mostrar "Expressão é ESTRANHA";
endif

stop
@enduml
